//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLaboratory
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedLaboratoryEntities : DbContext
    {
        public MedLaboratoryEntities()
            : base("name=MedLaboratoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Авторизация> Авторизация { get; set; }
        public virtual DbSet<Анализатор> Анализатор { get; set; }
        public virtual DbSet<Биоматериал> Биоматериал { get; set; }
        public virtual DbSet<Должность> Должность { get; set; }
        public virtual DbSet<Другое> Другое { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<Используемый_материал> Используемый_материал { get; set; }
        public virtual DbSet<История> История { get; set; }
        public virtual DbSet<Материал> Материал { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Работа_анализатора> Работа_анализатора { get; set; }
        public virtual DbSet<Сданный_биоматериал> Сданный_биоматериал { get; set; }
        public virtual DbSet<Статус> Статус { get; set; }
        public virtual DbSet<Страховая_компания> Страховая_компания { get; set; }
        public virtual DbSet<Счет_страховой> Счет_страховой { get; set; }
        public virtual DbSet<Тип_страхового_полиса> Тип_страхового_полиса { get; set; }
        public virtual DbSet<Услуга> Услуга { get; set; }
        public virtual DbSet<Услуги_заказа> Услуги_заказа { get; set; }
    }
}
