//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLaboratory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Используемый_материал
    {
        public int Код_используемого_материала { get; set; }
        public Nullable<int> Код_услуги_заказа { get; set; }
        public Nullable<int> Код_материала { get; set; }
        public Nullable<int> Количество { get; set; }
    
        public virtual Материал Материал { get; set; }
        public virtual Услуги_заказа Услуги_заказа { get; set; }
    }
}
