//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLaboratory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Работа_анализатора
    {
        public int Код_работы_анализватора { get; set; }
        public Nullable<int> Код_услуги_заказа { get; set; }
        public Nullable<int> Код_анализатора { get; set; }
        public Nullable<System.DateTime> Дата_и_время_выполнения_услуги { get; set; }
    
        public virtual Анализатор Анализатор { get; set; }
        public virtual Услуги_заказа Услуги_заказа { get; set; }
    }
}
