//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLaboratory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Счет_страховой
    {
        public int Код_счета_страховой { get; set; }
        public Nullable<int> Код_бухгалтера { get; set; }
        public Nullable<int> Код_заказа { get; set; }
        public Nullable<decimal> Сумма { get; set; }
        public Nullable<System.DateTime> Начало_периода_оплаты { get; set; }
        public Nullable<System.DateTime> Окночание_переода_оплаты { get; set; }
    
        public virtual Заказ Заказ { get; set; }
        public virtual Пользователи Пользователи { get; set; }
    }
}
