//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLaboratory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Услуги_заказа
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Услуги_заказа()
        {
            this.Используемый_материал = new HashSet<Используемый_материал>();
            this.Работа_анализатора = new HashSet<Работа_анализатора>();
            this.Сданный_биоматериал = new HashSet<Сданный_биоматериал>();
        }
    
        public int Код_услуги_заказа { get; set; }
        public Nullable<int> Код_заказа { get; set; }
        public Nullable<int> Код_услуг { get; set; }
        public Nullable<int> Код_статуса_услуги { get; set; }
        public Nullable<System.DateTime> Дата_и_время_выполнения { get; set; }
        public Nullable<double> Результат { get; set; }
        public Nullable<int> Код_сотрудника { get; set; }
        public Nullable<double> Среднее_отклонение { get; set; }
    
        public virtual Заказ Заказ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Используемый_материал> Используемый_материал { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Работа_анализатора> Работа_анализатора { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сданный_биоматериал> Сданный_биоматериал { get; set; }
        public virtual Статус Статус { get; set; }
        public virtual Услуга Услуга { get; set; }
    }
}
