//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLaboratory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сданный_биоматериал
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сданный_биоматериал()
        {
            this.Услуги_заказа = new HashSet<Услуги_заказа>();
        }
    
        public int Код_сданного_биоматериала { get; set; }
        public Nullable<int> Код_биоматериала { get; set; }
        public Nullable<double> Количество { get; set; }
    
        public virtual Биоматериал Биоматериал { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Услуги_заказа> Услуги_заказа { get; set; }
    }
}
