//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLaboratory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сданный_биоматериал
    {
        public int Код_сданного_биоматериала { get; set; }
        public Nullable<int> Код_услуги_заказа { get; set; }
        public Nullable<int> Код_биоматериала { get; set; }
        public Nullable<double> Количество { get; set; }
        public Nullable<System.DateTime> Время_сдачи { get; set; }
    
        public virtual Биоматериал Биоматериал { get; set; }
        public virtual Услуги_заказа Услуги_заказа { get; set; }
    }
}
